-- 코드를 입력하세요
WITH TMP AS(
    
    SELECT FLAVOR, SUM(TOTAL_ORDER) as TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
    
)

SELECT F.FLAVOR
FROM FIRST_HALF F JOIN TMP T on F.FLAVOR = T.FLAVOR
ORDER BY F.TOTAL_ORDER + T.TOTAL_ORDER DESC LIMIT 3 
