-- 코드를 입력하세요

SELECT b.USER_ID, b.NICKNAME, sum(a.Price) as TOTAL_SALES
FROM USED_GOODS_BOARD a JOIN USED_GOODS_USER b on a.WRITER_ID = b.USER_ID
WHERE STATUS = 'DONE'
GROUP BY USER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES asc