WITH TMP AS(
    SELECT BOARD_ID
    FROM USED_GOODS_BOARD 
    ORDER BY VIEWS DESC
    LIMIT 1
)

SELECT concat("/home/grep/src/",BOARD_ID,"/",FILE_ID,FILE_NAME,FILE_EXT) as FILE_PATH
FROM USED_GOODS_FILE 
WHERE BOARD_ID IN (SELECT * FROM TMP)
ORDER BY FILE_ID DESC